# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-06-10 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theorems', '0002_keyword_theorem_keyword_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theorem_keyword_link',
            unique_together=set([('theorem', 'keyword')]),
        ),
    ]
